export interface SkillTemplateMilestone {
  tier: number;
  title: string;
  description?: string;
  type: 'quantity' | 'consistency' | 'achievement' | 'quality';
  verify: 'platform_auto' | 'platform_test' | 'evidence' | 'self_declare';
  config: Record<string, unknown>;
}

export interface SkillTemplateState {
  key: string;
  label: string;
  source: 'platform_auto' | 'user_confirmed';
  expiresAfterDays: number;
}

export interface SkillTemplate {
  id: string;
  name: string;
  categoryKey: string;
  description: string;
  milestones: SkillTemplateMilestone[];
  defaultStates: SkillTemplateState[];
}

export const SKILL_TEMPLATES: SkillTemplate[] = [
  {
    id: 'french',
    name: '法语',
    categoryKey: '语言能力',
    description: '法语听说读写综合能力',
    milestones: [
      // 入门 (tier 1)
      { tier: 1, title: '掌握 500 词', type: 'quantity', verify: 'platform_auto',
        config: { source: 'vocab', metric: 'mastered_count', threshold: 500 } },
      { tier: 1, title: '词汇抽查正确率 > 80%', type: 'quality', verify: 'platform_test',
        config: { testType: 'vocab_quiz', sampleSize: 30, passRate: 0.8 } },
      { tier: 1, title: '完成基础语法学习模块', type: 'achievement', verify: 'platform_auto',
        config: { source: 'skill_learning', skillId: 'french-grammar', metric: 'completed', threshold: 1 } },
      // 基础 (tier 2)
      { tier: 2, title: '掌握 2000 词', type: 'quantity', verify: 'platform_auto',
        config: { source: 'vocab', metric: 'mastered_count', threshold: 2000 } },
      { tier: 2, title: 'SRS 复习正确率 > 75%', type: 'quality', verify: 'platform_auto',
        config: { source: 'vocab', metric: 'srs_accuracy', threshold: 0.75 } },
      { tier: 2, title: '通过中级阅读理解测试', type: 'quality', verify: 'platform_test',
        config: { testType: 'reading_comprehension', level: 'intermediate' } },
      // 胜任 (tier 3)
      { tier: 3, title: '掌握 5000 词', type: 'quantity', verify: 'platform_auto',
        config: { source: 'vocab', metric: 'mastered_count', threshold: 5000 } },
      { tier: 3, title: '精读 10 篇法语长文', type: 'quantity', verify: 'platform_auto',
        config: { source: 'article', metric: 'french_articles_read', threshold: 10 } },
      { tier: 3, title: '通过 DELF B1 或同等认证', type: 'achievement', verify: 'evidence',
        config: { evidenceType: 'certificate', description: '上传 DELF B1 成绩单或同等证明' } },
      // 精通 (tier 4)
      { tier: 4, title: '掌握 10000 词', type: 'quantity', verify: 'platform_auto',
        config: { source: 'vocab', metric: 'mastered_count', threshold: 10000 } },
      { tier: 4, title: '读完 5 本法语原著', type: 'quantity', verify: 'evidence',
        config: { evidenceType: 'screenshot', description: '提交阅读记录或书评' } },
      { tier: 4, title: '通过 DELF B2 或同等认证', type: 'achievement', verify: 'evidence',
        config: { evidenceType: 'certificate', description: '上传 DELF B2 成绩单' } },
      // 卓越 (tier 5)
      { tier: 5, title: '通过 DALF C1 或同等认证', type: 'achievement', verify: 'evidence',
        config: { evidenceType: 'certificate', description: '上传 DALF C1 成绩单' } },
      { tier: 5, title: '能用法语进行专业写作或演讲', type: 'achievement', verify: 'evidence',
        config: { evidenceType: 'link', description: '提交法语论文、演讲视频等' } },
    ],
    defaultStates: [
      { key: 'vocab_count', label: '词汇量', source: 'platform_auto', expiresAfterDays: 0 },
      { key: 'srs_accuracy', label: 'SRS正确率', source: 'platform_auto', expiresAfterDays: 0 },
      { key: 'certification', label: '最高认证', source: 'user_confirmed', expiresAfterDays: 0 },
    ],
  },
  {
    id: 'running',
    name: '跑步',
    categoryKey: '身体运动',
    description: '跑步耐力、速度与持续性',
    milestones: [
      { tier: 1, title: '单次完成 3 公里', type: 'achievement', verify: 'self_declare',
        config: { prompt: '确认你能单次不间断跑完 3 公里' } },
      { tier: 1, title: '连续 4 周每周跑步至少 1 次', type: 'consistency', verify: 'platform_auto',
        config: { source: 'habit', metric: 'streak_weeks', threshold: 4 } },
      { tier: 2, title: '单次完成 5 公里', type: 'achievement', verify: 'evidence',
        config: { evidenceType: 'screenshot', description: '提交运动app截图' } },
      { tier: 2, title: '5公里配速 < 7分钟/公里', type: 'quality', verify: 'evidence',
        config: { evidenceType: 'screenshot', description: '提交配速截图' } },
      { tier: 2, title: '连续 12 周每周跑步', type: 'consistency', verify: 'platform_auto',
        config: { source: 'habit', metric: 'streak_weeks', threshold: 12 } },
      { tier: 3, title: '单次完成 10 公里', type: 'achievement', verify: 'evidence',
        config: { evidenceType: 'screenshot', description: '提交运动记录' } },
      { tier: 3, title: '连续 6 个月每周跑步', type: 'consistency', verify: 'platform_auto',
        config: { source: 'habit', metric: 'streak_weeks', threshold: 26 } },
      { tier: 3, title: '累计跑量 500 公里', type: 'quantity', verify: 'evidence',
        config: { evidenceType: 'screenshot', description: '提交累计跑量截图' } },
      { tier: 4, title: '完成半马 21 公里', type: 'achievement', verify: 'evidence',
        config: { evidenceType: 'certificate', description: '提交完赛证书或运动记录' } },
      { tier: 4, title: '5公里配速 < 5分30秒/公里', type: 'quality', verify: 'evidence',
        config: { evidenceType: 'screenshot', description: '提交配速截图' } },
      { tier: 5, title: '完成全马 42 公里', type: 'achievement', verify: 'evidence',
        config: { evidenceType: 'certificate', description: '提交完赛证书' } },
      { tier: 5, title: '半马成绩 < 1小时50分', type: 'quality', verify: 'evidence',
        config: { evidenceType: 'certificate', description: '提交完赛成绩' } },
    ],
    defaultStates: [
      { key: 'single_run_km', label: '单次跑步能力(km)', source: 'user_confirmed', expiresAfterDays: 90 },
      { key: 'weekly_frequency', label: '每周跑步次数', source: 'platform_auto', expiresAfterDays: 0 },
      { key: 'pace_per_km', label: '5公里配速', source: 'user_confirmed', expiresAfterDays: 90 },
    ],
  },
  {
    id: 'programming',
    name: '编程',
    categoryKey: '数理逻辑',
    description: '软件开发与编程能力',
    milestones: [
      { tier: 1, title: '完成一个编程入门课程', type: 'achievement', verify: 'evidence',
        config: { evidenceType: 'certificate', description: '提交课程完成截图或证书' } },
      { tier: 1, title: '独立完成一个简单程序', type: 'achievement', verify: 'evidence',
        config: { evidenceType: 'link', description: '提交代码仓库链接' } },
      { tier: 2, title: '掌握一门编程语言的核心语法', type: 'achievement', verify: 'self_declare',
        config: { prompt: '确认你能熟练使用一门编程语言的核心语法（变量、循环、函数、类等）' } },
      { tier: 2, title: '独立完成一个完整项目', type: 'achievement', verify: 'evidence',
        config: { evidenceType: 'link', description: '提交项目链接（GitHub等）' } },
      { tier: 2, title: '理解基本数据结构与算法', type: 'quality', verify: 'self_declare',
        config: { prompt: '确认你理解数组、链表、栈、队列、排序、搜索等基本概念' } },
      { tier: 3, title: '掌握两门以上编程语言', type: 'achievement', verify: 'self_declare',
        config: { prompt: '确认你能熟练使用两门以上编程语言' } },
      { tier: 3, title: '有实际上线的项目或产品', type: 'achievement', verify: 'evidence',
        config: { evidenceType: 'link', description: '提交上线项目链接' } },
      { tier: 3, title: '能独立设计和实现中等复杂度系统', type: 'quality', verify: 'evidence',
        config: { evidenceType: 'link', description: '提交系统设计文档或代码' } },
      { tier: 4, title: '深入掌握系统设计与架构', type: 'achievement', verify: 'evidence',
        config: { evidenceType: 'link', description: '提交架构设计文档或技术博客' } },
      { tier: 4, title: '对开源项目有实质贡献', type: 'achievement', verify: 'evidence',
        config: { evidenceType: 'link', description: '提交 PR 链接' } },
      { tier: 5, title: '在技术社区有影响力（演讲/著作/开源项目星标 1000+）', type: 'achievement', verify: 'evidence',
        config: { evidenceType: 'link', description: '提交影响力证据' } },
      { tier: 5, title: '能设计和领导大型复杂系统', type: 'achievement', verify: 'evidence',
        config: { evidenceType: 'link', description: '提交项目或团队经历证明' } },
    ],
    defaultStates: [
      { key: 'primary_language', label: '主力语言', source: 'user_confirmed', expiresAfterDays: 0 },
      { key: 'active_projects', label: '活跃项目数', source: 'user_confirmed', expiresAfterDays: 90 },
      { key: 'github_contributions', label: 'GitHub 年度贡献', source: 'user_confirmed', expiresAfterDays: 180 },
    ],
  },
  {
    id: 'guitar',
    name: '吉他',
    categoryKey: '艺术创作',
    description: '吉他演奏技能',
    milestones: [
      { tier: 1, title: '学会基本和弦（C, G, D, Em, Am）', type: 'achievement', verify: 'self_declare',
        config: { prompt: '确认你能流畅弹奏 C, G, D, Em, Am 这5个基本和弦' } },
      { tier: 1, title: '能弹唱一首简单歌曲', type: 'achievement', verify: 'evidence',
        config: { evidenceType: 'link', description: '录制一段弹唱视频' } },
      { tier: 2, title: '掌握大横按（F, Bm等）', type: 'achievement', verify: 'self_declare',
        config: { prompt: '确认你能流畅弹奏大横按和弦' } },
      { tier: 2, title: '能弹奏指弹简单曲目', type: 'achievement', verify: 'evidence',
        config: { evidenceType: 'link', description: '录制指弹演奏视频' } },
      { tier: 2, title: '连续练习 3 个月每周至少 3 次', type: 'consistency', verify: 'platform_auto',
        config: { source: 'habit', metric: 'streak_weeks', threshold: 12 } },
      { tier: 3, title: '能完整演奏 10 首中等难度曲目', type: 'quantity', verify: 'evidence',
        config: { evidenceType: 'link', description: '提交演奏视频或曲目列表' } },
      { tier: 3, title: '掌握基本乐理（调式、音阶）', type: 'quality', verify: 'self_declare',
        config: { prompt: '确认你理解大小调、五声音阶、自然音阶等基本乐理' } },
      { tier: 4, title: '能即兴演奏', type: 'achievement', verify: 'evidence',
        config: { evidenceType: 'link', description: '录制即兴演奏视频' } },
      { tier: 4, title: '有公开演出经历', type: 'achievement', verify: 'evidence',
        config: { evidenceType: 'screenshot', description: '提交演出照片或海报' } },
      { tier: 5, title: '能编曲或创作原创作品', type: 'achievement', verify: 'evidence',
        config: { evidenceType: 'link', description: '提交原创作品' } },
      { tier: 5, title: '通过专业吉他考级（8级以上）或同等水平认证', type: 'achievement', verify: 'evidence',
        config: { evidenceType: 'certificate', description: '提交考级证书' } },
    ],
    defaultStates: [
      { key: 'practice_frequency', label: '每周练习次数', source: 'platform_auto', expiresAfterDays: 0 },
      { key: 'repertoire_count', label: '能演奏的曲目数', source: 'user_confirmed', expiresAfterDays: 180 },
    ],
  },
  {
    id: 'cooking',
    name: '烹饪',
    categoryKey: '生活实践',
    description: '日常烹饪与料理技能',
    milestones: [
      { tier: 1, title: '能独立做 5 道家常菜', type: 'quantity', verify: 'self_declare',
        config: { prompt: '确认你能独立完成至少 5 道家常菜的制作' } },
      { tier: 1, title: '掌握基本烹饪技法（炒、煮、蒸、炖）', type: 'quality', verify: 'self_declare',
        config: { prompt: '确认你熟练掌握炒、煮、蒸、炖这四种基本烹饪方法' } },
      { tier: 2, title: '能做 15 道以上菜品', type: 'quantity', verify: 'self_declare',
        config: { prompt: '确认你能独立完成 15 道以上菜品' } },
      { tier: 2, title: '掌握一种菜系的基本做法', type: 'achievement', verify: 'self_declare',
        config: { prompt: '确认你对某一菜系（如川菜、粤菜、西餐等）有系统了解' } },
      { tier: 2, title: '能做出受朋友好评的一顿饭', type: 'quality', verify: 'evidence',
        config: { evidenceType: 'screenshot', description: '拍照记录你做的一顿完整餐食' } },
      { tier: 3, title: '能制作复杂菜品（如烘焙、发酵食品）', type: 'achievement', verify: 'evidence',
        config: { evidenceType: 'screenshot', description: '拍照记录复杂料理过程' } },
      { tier: 3, title: '掌握两种以上菜系', type: 'achievement', verify: 'self_declare',
        config: { prompt: '确认你对两种以上菜系有系统了解和实践' } },
      { tier: 4, title: '能创作原创菜品', type: 'achievement', verify: 'evidence',
        config: { evidenceType: 'screenshot', description: '记录你的原创菜品及制作过程' } },
      { tier: 4, title: '获得烹饪相关认证或奖项', type: 'achievement', verify: 'evidence',
        config: { evidenceType: 'certificate', description: '提交证书或获奖证明' } },
      { tier: 5, title: '能教授烹饪课程或出版食谱', type: 'achievement', verify: 'evidence',
        config: { evidenceType: 'link', description: '提交课程或食谱链接' } },
      { tier: 5, title: '在烹饪领域有公认成就', type: 'achievement', verify: 'evidence',
        config: { evidenceType: 'link', description: '提交相关证明' } },
    ],
    defaultStates: [
      { key: 'dish_count', label: '能做的菜品数', source: 'user_confirmed', expiresAfterDays: 180 },
      { key: 'cuisine_styles', label: '掌握的菜系', source: 'user_confirmed', expiresAfterDays: 0 },
    ],
  },
  {
    id: 'swimming',
    name: '游泳',
    categoryKey: '身体运动',
    description: '游泳技能与体能',
    milestones: [
      { tier: 1, title: '能连续游 50 米', type: 'achievement', verify: 'self_declare',
        config: { prompt: '确认你能连续游完 50 米不停歇' } },
      { tier: 1, title: '掌握一种标准泳姿', type: 'achievement', verify: 'self_declare',
        config: { prompt: '确认你至少掌握蛙泳、自由泳、仰泳其中一种标准泳姿' } },
      { tier: 2, title: '能连续游 400 米', type: 'achievement', verify: 'evidence',
        config: { evidenceType: 'screenshot', description: '提交运动手表或泳池记录截图' } },
      { tier: 2, title: '掌握两种泳姿', type: 'quality', verify: 'self_declare',
        config: { prompt: '确认你熟练掌握两种标准泳姿' } },
      { tier: 2, title: '连续 12 周每周游泳', type: 'consistency', verify: 'platform_auto',
        config: { source: 'habit', metric: 'streak_weeks', threshold: 12 } },
      { tier: 3, title: '能连续游 1500 米', type: 'achievement', verify: 'evidence',
        config: { evidenceType: 'screenshot', description: '提交游泳记录' } },
      { tier: 3, title: '掌握三种以上泳姿', type: 'quality', verify: 'self_declare',
        config: { prompt: '确认你熟练掌握三种以上标准泳姿' } },
      { tier: 4, title: '参加游泳比赛并完赛', type: 'achievement', verify: 'evidence',
        config: { evidenceType: 'certificate', description: '提交参赛证明' } },
      { tier: 4, title: '100米自由泳 < 1分30秒', type: 'quality', verify: 'evidence',
        config: { evidenceType: 'screenshot', description: '提交计时成绩' } },
      { tier: 5, title: '完成公开水域长距离游泳（3公里+）', type: 'achievement', verify: 'evidence',
        config: { evidenceType: 'certificate', description: '提交完赛证书' } },
      { tier: 5, title: '获得游泳教练或救生员资质', type: 'achievement', verify: 'evidence',
        config: { evidenceType: 'certificate', description: '提交资质证书' } },
    ],
    defaultStates: [
      { key: 'max_distance', label: '单次最长距离(m)', source: 'user_confirmed', expiresAfterDays: 90 },
      { key: 'strokes_mastered', label: '掌握的泳姿', source: 'user_confirmed', expiresAfterDays: 0 },
    ],
  },
  {
    id: 'drawing',
    name: '绘画',
    categoryKey: '艺术创作',
    description: '绘画与视觉艺术创作',
    milestones: [
      { tier: 1, title: '完成 10 幅基础练习作品（素描/速写）', type: 'quantity', verify: 'evidence',
        config: { evidenceType: 'screenshot', description: '上传练习作品照片' } },
      { tier: 1, title: '掌握基本透视和比例', type: 'quality', verify: 'self_declare',
        config: { prompt: '确认你理解一点透视、两点透视和基本人体比例' } },
      { tier: 2, title: '完成 30 幅以上作品', type: 'quantity', verify: 'evidence',
        config: { evidenceType: 'screenshot', description: '上传作品集' } },
      { tier: 2, title: '掌握一种上色技法（水彩/数字绘画/油画等）', type: 'achievement', verify: 'evidence',
        config: { evidenceType: 'screenshot', description: '上传上色作品' } },
      { tier: 3, title: '形成个人风格并有作品集', type: 'achievement', verify: 'evidence',
        config: { evidenceType: 'link', description: '提交在线作品集链接' } },
      { tier: 3, title: '获得他人委托创作', type: 'quality', verify: 'evidence',
        config: { evidenceType: 'screenshot', description: '提交委托创作记录' } },
      { tier: 4, title: '参加画展或获得奖项', type: 'achievement', verify: 'evidence',
        config: { evidenceType: 'certificate', description: '提交参展或获奖证明' } },
      { tier: 4, title: '通过绘画获得收入', type: 'achievement', verify: 'evidence',
        config: { evidenceType: 'screenshot', description: '提交收入证明' } },
      { tier: 5, title: '举办个人画展', type: 'achievement', verify: 'evidence',
        config: { evidenceType: 'screenshot', description: '提交画展记录' } },
      { tier: 5, title: '在艺术领域有公认影响力', type: 'achievement', verify: 'evidence',
        config: { evidenceType: 'link', description: '提交影响力证据' } },
    ],
    defaultStates: [
      { key: 'works_count', label: '作品数量', source: 'user_confirmed', expiresAfterDays: 180 },
      { key: 'medium', label: '常用媒介', source: 'user_confirmed', expiresAfterDays: 0 },
    ],
  },
  {
    id: 'investing',
    name: '投资',
    categoryKey: '专业技能',
    description: '个人投资与理财能力',
    milestones: [
      { tier: 1, title: '了解基本投资品种（股票、基金、债券）', type: 'achievement', verify: 'self_declare',
        config: { prompt: '确认你理解股票、基金、债券的基本概念和区别' } },
      { tier: 1, title: '开设投资账户并完成首笔投资', type: 'achievement', verify: 'self_declare',
        config: { prompt: '确认你已开设证券/基金账户并完成了首次投资' } },
      { tier: 2, title: '制定个人投资计划', type: 'achievement', verify: 'self_declare',
        config: { prompt: '确认你有书面的个人投资计划（资产配置比例、目标收益等）' } },
      { tier: 2, title: '理解基本面和技术面分析', type: 'quality', verify: 'self_declare',
        config: { prompt: '确认你能看懂财报基本指标（PE、PB、ROE等）和K线图' } },
      { tier: 2, title: '持续投资满 1 年', type: 'consistency', verify: 'self_declare',
        config: { prompt: '确认你已持续进行投资操作满一年' } },
      { tier: 3, title: '投资组合实现正收益满 3 年', type: 'quality', verify: 'evidence',
        config: { evidenceType: 'screenshot', description: '提交投资账户收益截图' } },
      { tier: 3, title: '通过证券从业或基金从业考试', type: 'achievement', verify: 'evidence',
        config: { evidenceType: 'certificate', description: '提交考试通过证明' } },
      { tier: 4, title: '管理资产超过 50 万', type: 'achievement', verify: 'self_declare',
        config: { prompt: '确认你管理的投资资产超过50万元' } },
      { tier: 4, title: '年化收益连续 5 年跑赢通胀', type: 'quality', verify: 'evidence',
        config: { evidenceType: 'screenshot', description: '提交投资业绩记录' } },
      { tier: 5, title: '具有 CFA 或同等专业资质', type: 'achievement', verify: 'evidence',
        config: { evidenceType: 'certificate', description: '提交 CFA 或同等证书' } },
      { tier: 5, title: '管理他人资金或发表投资研究', type: 'achievement', verify: 'evidence',
        config: { evidenceType: 'link', description: '提交相关证据' } },
    ],
    defaultStates: [
      { key: 'portfolio_size', label: '投资组合规模', source: 'user_confirmed', expiresAfterDays: 180 },
      { key: 'ytd_return', label: '本年收益率', source: 'user_confirmed', expiresAfterDays: 90 },
    ],
  },
];
