import { sqliteTable, text, integer, uniqueIndex } from 'drizzle-orm/sqlite-core';

// Cached daily insights generated by LLM
export const coachDailyInsights = sqliteTable('coach_daily_insights', {
  id: integer('id').primaryKey({ autoIncrement: true }),
  date: text('date').notNull(), // YYYY-MM-DD
  content: text('content').notNull(),
  createdAt: integer('created_at', { mode: 'number' }).notNull(),
}, (table) => [
  uniqueIndex('idx_coach_daily_insights_date').on(table.date),
]);
